Add plpython3, pgvector, and pgai extensions
timescale/timescaledb-docker pull request #249
Opened 2024-06-04 16:35 UTC by jgpruitt

This adds several new extensions to the image including:

1. plpython3
2. pgvector
3. pgai

To add plpython3 on pg16, we needed to bump from Alpine 3.18 to Alpine 3.20. Alpine 3.20 does not have plpython3 packages for pg13. Timescaledb no longer supports pg13 anyway, so we dropped support for it.

2024-06-04 16:38 UTC, svenklemm commented
Might have to wait until after 2.15.2 is out as we still need pg13 for that

2024-06-05 19:26 UTC, fabriziomello requested changes
Need to wait until 2.15.2 is released because we need PG13 images.

2024-06-06 03:30 UTC, svenklemm approved these changes

2024-06-07 16:00 UTC, fabriziomello approved these changes
I just need to finish this workflow with success before merge it: https://github.com/timescale/release-build-scripts/actions/runs/9418425087

Also we need to make sure that all packages are properly uploaded to packagecloud: https://packagecloud.io/app/timescale/timescaledb/search?q=2.15.2&filter=all&filter=all&dist=noble

2024-06-07 17:30 UTC, merged

2024-06-11 03:15 UTC, grrowl commented
When can we expect this to make it into the official docker hub images (under `latest-pg16`)?

2024-06-11 15:35 UTC, svenklemm commented
I've triggered docker image rebuild so should be available in an hour roughly